Load Data

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [ ]:
from kaggle import api
from kaggle.api.kaggle_api_extended import KaggleApi
api = KaggleApi()
api.authenticate()



In [ ]:
!kaggle competitions download -c playground-series-s4e7

 98% 242M/247M [00:01<00:00, 212MB/s]
100% 247M/247M [00:01<00:00, 214MB/s]


In [ ]:
import zipfile
z=zipfile.ZipFile('/content/playground-series-s4e7.zip','r')
z.extractall('/content')
z.close()

Data preprocessing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [ ]:
df=pd.read_csv('/content/train.csv')

In [ ]:
df.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   0    Male   21                1         35.0                   0   
1   1    Male   43                1         28.0                   0   
2   2  Female   25                1         14.0                   1   
3   3  Female   35                1          1.0                   0   
4   4  Female   36                1         15.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes         65101.0                 124.0      187   
1   > 2 Years            Yes         58911.0                  26.0      288   
2    < 1 Year             No         38043.0                 152.0      254   
3    1-2 Year            Yes          2630.0                 156.0       76   
4    1-2 Year             No         31951.0                 152.0      294   

   Response  
0         0  
1         1  
2         0  
3         0  
4         0

In [ ]:
df.describe()

id           Age  Driving_License   Region_Code  \
count  1.150480e+07  1.150480e+07     1.150480e+07  1.150480e+07   
mean   5.752398e+06  3.838356e+01     9.980220e-01  2.641869e+01   
std    3.321149e+06  1.499346e+01     4.443120e-02  1.299159e+01   
min    0.000000e+00  2.000000e+01     0.000000e+00  0.000000e+00   
25%    2.876199e+06  2.400000e+01     1.000000e+00  1.500000e+01   
50%    5.752398e+06  3.600000e+01     1.000000e+00  2.800000e+01   
75%    8.628598e+06  4.900000e+01     1.000000e+00  3.500000e+01   
max    1.150480e+07  8.500000e+01     1.000000e+00  5.200000e+01   

       Previously_Insured  Annual_Premium  Policy_Sales_Channel       Vintage  \
count        1.150480e+07    1.150480e+07          1.150480e+07  1.150480e+07   
mean         4.629966e-01    3.046137e+04          1.124254e+02  1.638977e+02   
std          4.986289e-01    1.645475e+04          5.403571e+01  7.997953e+01   
min          0.000000e+00    2.630000e+03          1.000000e+00  1.000000e+01   
25%          0.000000e+00    2.527700e+04          2.900000e+01  9.900000e+01   
50%          0.000000e+00    3.182400e+04          1.510000e+02  1.660000e+02   
75%          1.000000e+00    3.945100e+04          1.520000e+02  2.320000e+02   
max          1.000000e+00    5.401650e+05          1.630000e+02  2.990000e+02   

           Response  
count  1.150480e+07  
mean   1.229973e-01  
std    3.284341e-01  
min    0.000000e+00  
25%    0.000000e+00  
50%    0.000000e+00  
75%    0.000000e+00  
max    1.000000e+00

In [ ]:
df.isnull().sum().sum()

0

In [ ]:
df_test=pd.read_csv('/content/test.csv')
df_test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  11504798  Female   20                1         47.0                   0   
1  11504799    Male   47                1         28.0                   0   
2  11504800    Male   47                1         43.0                   0   
3  11504801  Female   22                1         47.0                   1   
4  11504802    Male   51                1         19.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No          2630.0                 160.0      228  
1    1-2 Year            Yes         37483.0                 124.0      123  
2    1-2 Year            Yes          2630.0                  26.0      271  
3    < 1 Year             No         24502.0                 152.0      115  
4    1-2 Year             No         34115.0                 124.0      148

In [ ]:
df['Region_Code'].unique()

array([35. , 28. , 14. ,  1. , 15. , 47. , 45. ,  8. , 11. ,  3. , 10. ,
       12. , 37. , 50. , 30. , 46. , 29. , 16. , 26. , 25. , 41. , 48. ,
        7. ,  4. , 24. , 36. , 33. ,  2. ,  9. , 27. , 18. , 43. , 49. ,
       17. , 13. , 38. ,  6. , 21. , 23. ,  0. , 19. ,  5. , 39. , 44. ,
       20. , 40. , 22. , 32. , 42. , 31. , 34. , 51. , 52. , 39.2])

In [ ]:
df_test['Region_Code'].unique()

array([47., 28., 43., 19., 30., 20., 37., 48., 29., 11., 21., 10.,  0.,
       36., 41., 45., 35.,  8., 40., 39., 32., 34.,  2.,  6., 31., 49.,
        9., 46., 14., 18., 12., 15.,  3.,  4., 50., 22.,  7., 17., 33.,
       25., 24., 16., 27.,  5., 13., 38., 23., 44., 26.,  1., 42., 51.,
       52.])

In [ ]:
df['Age'].unique()

array([21, 43, 25, 35, 36, 31, 23, 47, 26, 66, 22, 27, 24, 79, 34, 20, 42,
       40, 50, 67, 63, 46, 37, 30, 53, 32, 28, 58, 48, 59, 52, 39, 44, 33,
       41, 57, 51, 45, 68, 74, 29, 49, 55, 61, 60, 65, 54, 38, 56, 71, 62,
       70, 73, 64, 69, 72, 78, 80, 76, 75, 77, 81, 83, 82, 84, 85])

In [ ]:
df_test['Age'].unique()

array([20, 47, 22, 51, 23, 21, 72, 33, 67, 34, 25, 24, 45, 65, 40, 35, 26,
       41, 66, 31, 39, 80, 52, 28, 50, 59, 57, 53, 79, 49, 44, 42, 74, 62,
       43, 56, 61, 76, 46, 38, 30, 71, 27, 54, 75, 70, 55, 32, 48, 29, 69,
       73, 60, 58, 63, 37, 36, 64, 68, 77, 78, 82, 83, 81, 84, 85])

In [ ]:
df['Policy_Sales_Channel'].unique()

array([124.,  26., 152., 156., 160.,   8.,  31., 157.,  60., 122.,  15.,
        30., 147.,   1.,  63., 136., 154.,  18., 135., 151.,   3.,  10.,
        55., 108.,   7.,  29., 163.,  13., 133., 145.,  25.,  12., 109.,
        23.,  78.,   4., 153., 150., 146., 120., 107., 155.,  61.,  14.,
        45.,  11.,  19.,  24.,  52., 132., 125.,  59.,  16.,  22.,  56.,
        20., 148., 158., 159., 139.,   9., 113., 121.,  21., 111.,  64.,
       116., 103., 128.,  65.,  37.,  91., 129., 127., 106., 140.,  35.,
       131.,  17.,  93.,  90.,  36., 118.,  54.,  62., 138.,  42.,  46.,
        86.,  80.,  68., 119.,  94.,  48.,  47.,  83.,  97.,  70.,  53.,
        44., 114.,  98.,  88., 110.,  32., 126.,  96.,  99., 130.,  66.,
       105.,  51.,  38., 137.,  89.,  81.,  92., 117.,  73.,  69.,  49.,
        87.,  33.,  39.,  50., 123.,  75., 101., 115., 100.,  95.,  57.,
        71., 134.,  82.,   6.,  58., 104.,  41.,  40.,   2.,  79.,  34.,
        76.,  28.,  74.,  43.,  67.,  27., 112., 10

In [ ]:
df['Vintage'].unique()

array([187, 288, 254,  76, 294, 197, 190, 262,  36, 125, 215,  30, 203,
       259, 245, 150, 240, 242, 117, 151, 169, 185, 264,  38, 152, 284,
        25, 204, 181, 275,  95, 260, 222, 227, 273, 290,  70, 160,  81,
        20, 168, 267, 286, 130,  92, 171, 113, 158, 208,  42,  94, 189,
        84, 228, 194, 249, 129,  11, 120,  16, 298, 226, 159, 100, 230,
       295, 235, 217,  43, 132, 123, 131, 111, 127, 112, 182, 101,  34,
        80, 135, 292,  22, 163, 110,  29,  19,  77, 241, 232, 192, 280,
       252, 281, 253, 114,  74, 270,  17, 186,  61, 255,  21, 145,  27,
        63, 268, 176, 272,  48, 202, 274, 139, 246, 142,  78,  31, 193,
       137, 248, 108,  56, 238, 165, 256, 237, 247, 205,  15, 218, 282,
        24,  86,  90,  75,  54, 164, 278,  91,  49, 105, 251, 219,  53,
       102, 118, 236, 138,  47, 116, 115, 195,  71,  64, 224,  67,  83,
       201, 180, 279, 244, 206, 200, 257, 172, 283, 166, 261,  26, 155,
       285, 291, 128, 184,  65, 178,  79,  69,  40, 198, 234, 26

In [ ]:
df_test.isnull().sum().sum()

0

In [ ]:
df['Annual_Premium'].value_counts()

Annual_Premium
2630.0     2112561
38287.0       6363
39008.0       5285
38452.0       4721
28861.0       4671
            ...   
77839.0          1
67126.0          1
15999.0          1
59067.0          1
64538.0          1
Name: count, Length: 51728, dtype: int64

In [ ]:
df_test['Annual_Premium'].value_counts()

Annual_Premium
2630.0     1406800
38287.0       4293
39008.0       3529
38452.0       3149
28861.0       3148
            ...   
62158.0          1
69865.0          1
74350.0          1
56111.0          1
60767.0          1
Name: count, Length: 50044, dtype: int64

In [ ]:
df['Response'].value_counts()

Response
0    10089739
1     1415059
Name: count, dtype: int64

In [ ]:
# As annual premium has wide range of values so applying log before scaling
df['Annual_Premium_log'] = np.log1p(df['Annual_Premium'])
df_test['Annual_Premium_log'] = np.log1p(df_test['Annual_Premium'])

In [ ]:
print(df_test['Annual_Premium_log'])

0           7.875119
1          10.531669
2           7.875119
3          10.106551
4          10.437522
             ...    
7669861    10.852478
7669862    10.152377
7669863     7.875119
7669864    10.567901
7669865    10.221905
Name: Annual_Premium_log, Length: 7669866, dtype: float64


In [ ]:
# categorical_columns = ['Gender', 'Driving_License', 'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage']
# encoded_data_train = encoder.fit_transform(df[categorical_columns])
# encoded_data_test = encoder.transform(df_test[categorical_columns])

# encoded_region_code_train = encoder.fit_transform(df[['Region_Code']])
# encoded_region_code_test = encoder.transform(df_test[['Region_Code']])

# df[['Vintage_scaled', 'Policy_Sales_Channel_scaled']] = scaler.fit_transform(df[['Vintage', 'Policy_Sales_Channel']])
# df_test[['Vintage_scaled', 'Policy_Sales_Channel_scaled']] = scaler.transform(df_test[['Vintage', 'Policy_Sales_Channel']])

# df['Age_scaled','Annual_Premium_log_scaled'] = min_max_scaler.fit_transform(df[['Age','Annual_Premium_log']])
# df_test['Age_scaled','Annual_Premium_log_scaled'] = min_max_scaler.transform(df_test[['Age','Annual_Premium_log']])

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
encoder = OneHotEncoder()
scaler = StandardScaler()
min_max_scaler = MinMaxScaler()
label_encoder = LabelEncoder()
categorical_columns = ['Gender', 'Driving_License', 'Previously_Insured', 'Vehicle_Age', 'Vehicle_Damage']
numerical_columns = ['Age', 'Vintage', 'Policy_Sales_Channel', 'Annual_Premium_log','Region_Code']




preprocessor = ColumnTransformer(
    transformers=[
        ('cat', encoder, categorical_columns),  # apply OneHotEncoder to categorical columns
        ('num_scale', scaler, ['Vintage', 'Policy_Sales_Channel','Region_Code']),  # scale numerical columns
        ('num_minmax', min_max_scaler, ['Age', 'Annual_Premium_log']) #, ('num_label', label_encoder, ['Region_Code'])  # scale using MinMaxScaler
       # ,('num_passthrough', 'passthrough', ['Region_Code'])  # pass through Region_Code as numerical without scaling
    ],
    remainder='drop'  # drop any columns not specified
)

# Fit and transform training data
X_train_processed = preprocessor.fit_transform(df)

# Transform test data using the fitted transformer
X_test_processed = preprocessor.transform(df_test)









Pytorch way for training and test data

In [ ]:
import torch
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler

def preprocess_data(df, df_test):
    # Convert categorical columns to tensors
    categorical_cols = ['Gender', 'Vehicle_Age', 'Vehicle_Damage', 'Previously_Insured']
    categorical_data_train = df[categorical_cols].values
    categorical_data_test = df_test[categorical_cols].values

    # Convert numerical columns to tensors
    numerical_cols = ['Age', 'Driving_License', 'Region_Code', 'Annual_Premium_log', 'Policy_Sales_Channel', 'Vintage']
    numerical_data_train = df[numerical_cols].values.astype(float)
    numerical_data_test = df_test[numerical_cols].values.astype(float)

    # Perform one-hot encoding for categorical variables
    encoder = OneHotEncoder(sparse=False, drop='first')
    encoded_categorical_data_train = encoder.fit_transform(categorical_data_train)
    encoded_categorical_data_test = encoder.transform(categorical_data_test)

    # Extract the column index of Previously_Insured for one-hot encoding
    prev_insured_idx = categorical_cols.index('Previously_Insured')

    # Replace the original column with the one-hot encoded values
    encoded_categorical_tensor_train = torch.tensor(encoded_categorical_data_train, dtype=torch.float32)
    encoded_categorical_tensor_train = torch.cat((encoded_categorical_tensor_train[:, :prev_insured_idx],
                                                 encoded_categorical_tensor_train[:, prev_insured_idx + 1:]), dim=1)

    encoded_categorical_tensor_test = torch.tensor(encoded_categorical_data_test, dtype=torch.float32)
    encoded_categorical_tensor_test = torch.cat((encoded_categorical_tensor_test[:, :prev_insured_idx],
                                                encoded_categorical_tensor_test[:, prev_insured_idx + 1:]), dim=1)

    # Normalize numerical variables
    scaler = StandardScaler()
    scaled_numerical_data_train = scaler.fit_transform(numerical_data_train)
    scaled_numerical_data_test = scaler.transform(numerical_data_test)

    # Convert to PyTorch tensors
    scaled_numerical_tensor_train = torch.tensor(scaled_numerical_data_train, dtype=torch.float32)
    scaled_numerical_tensor_test = torch.tensor(scaled_numerical_data_test, dtype=torch.float32)

    # Separate into Xtrain, Ytrain, and Xtest tensors
    x_train = torch.cat((scaled_numerical_tensor_train, encoded_categorical_tensor_train), dim=1)
    y_train = torch.tensor(df['Response'].values, dtype=torch.float32)
    x_test = torch.cat((scaled_numerical_tensor_test, encoded_categorical_tensor_test), dim=1)

    return x_train, y_train, x_test





In [ ]:
x_train, y_train, x_test = preprocess_data(df, df_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


PyTorch model

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(x.device)

        out, _ = self.lstm(x, (h0, c0))

        out = self.fc(out[:, -1, :])
        out = self.sigmoid(out)
        return out.squeeze()


In [ ]:
# Model initialization

input_size = x_train.shape[1]
hidden_size = 64
num_layers = 1
output_size = 1

model = LSTMModel(input_size, hidden_size, num_layers, output_size)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)




In [ ]:
from torch.utils.data import TensorDataset, DataLoader

Xtrain_tensor = torch.tensor(x_train, dtype=torch.float32)
Ytrain_tensor = torch.tensor(y_train, dtype=torch.float32)
Xtest_tensor = torch.tensor(x_test, dtype=torch.float32)

# Create DataLoader for training data
train_dataset = TensorDataset(Xtrain_tensor, Ytrain_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)


<ipython-input-11-eabb4fc45717>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Xtrain_tensor = torch.tensor(x_train, dtype=torch.float32)
<ipython-input-11-eabb4fc45717>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Ytrain_tensor = torch.tensor(y_train, dtype=torch.float32)
<ipython-input-11-eabb4fc45717>:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  Xtest_tensor = torch.tensor(x_test, dtype=torch.float32)


In [ ]:
num_epochs = 10

model.train()

for epoch in range(num_epochs):
    epoch_loss = 0.0

    for inputs, labels in train_loader:
        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs.unsqueeze(1))

        # Calculate loss
        loss = criterion(outputs, labels)

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {epoch_loss / len(train_loader):.4f}')

torch.save(model.state_dict(), 'lstm_model.pth')


Epoch [1/10], Loss: 0.2729
Epoch [2/10], Loss: 0.2711
Epoch [3/10], Loss: 0.2704
Epoch [4/10], Loss: 0.2701
Epoch [5/10], Loss: 0.2699
Epoch [6/10], Loss: 0.2698
Epoch [7/10], Loss: 0.2696
Epoch [8/10], Loss: 0.2695
Epoch [9/10], Loss: 0.2695
Epoch [10/10], Loss: 0.2694


In [ ]:
# Delete model instance to free  memory
del model
# torch.cuda.empty_cache()  # Release cached memory


In [ ]:
# Xtest_tensor = torch.tensor(x_test, dtype=torch.float32).detach().cpu()
input_size = x_train.shape[1]
hidden_size = 64
num_layers = 1
output_size = 1
loaded_model = LSTMModel(input_size, hidden_size, num_layers, output_size)
loaded_model.load_state_dict(torch.load('/content/lstm_model.pth'))
loaded_model.eval()

# Predict probabilities for test set
with torch.no_grad():
    Ypred_prob = loaded_model(Xtest_tensor.unsqueeze(1)).cpu()

# Convert probabilities to binary predictions (0 or 1)
y_pred = torch.round(Ypred_prob).squeeze().detach().cpu().numpy()

# Example of how to use predictions
print(y_pred)


In [ ]:
submission_df = pd.DataFrame({'id': df_test['id'], 'Response': y_pred})

# Save to CSV
submission_df.to_csv('submission.csv', index=False)

In [ ]:
# Initialize train and test datasets
train_dataset = CustomDataset(df, categorical_columns, numerical_columns, encoder, scaler, min_max_scaler)
test_dataset = CustomDataset(df_test, categorical_columns, numerical_columns, encoder, scaler, min_max_scaler)

In [ ]:
X_train_processed.shape

(11504798, 16)

Model Development

In [ ]:
X_train = X_train_processed  # Features for training
y_train = df['Response'] # Target variable for training

X_test = X_test_processed  # Features for testing



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
# Initialize Random Forest Classifier
model = RandomForestClassifier(n_estimators=5, random_state=42)
# model = LogisticRegression(solver='lbfgs', max_iter=1000, random_state=0)
# model = DecisionTreeClassifier(random_state=42)
# model = SVC(kernel='sigmoid', C=1.0, gamma='scale', random_state=42)

# Train the classifier on the training data
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=5, random_state=42)

In [ ]:
# Predict response for test data
y_pred = model.predict(X_test)
print(f'Predictions are: \n {np.unique(y_pred)}')

Predictions are: 
 [0 1]


Save the output

In [ ]:
submission_df = pd.DataFrame({'id': df_test['id'], 'Response': y_pred})

# Save to CSV
submission_df.to_csv('submission.csv', index=False)